export const GET_DATA_STARTED = 'GET_DATA_STARTED';
export const GET_DATA_FAILURE = 'GET_DATA_FAILURE';
export const GET_DATA_SUCCESS = 'GET_DATA_SUCCESS';
export const FILTER_USERS_BY_NAMES = 'FILTER_USERS_BY_NAMES';
export const FILTER_USERS_BY_LASTNAMES = 'FILTER_USERS_BY_LASTNAMES';
export const FILTER_USERS_BY_AGE = 'FILTER_USERS_BY_AGE';
export const FILTER_USERS_BY_SEX = 'FILTER_USERS_BY_SEX';